/**
 * Gruntfile for freedom-social-email
 *
 * Autogenerated by https://github.com/freedomjs/generator-freedom
 **/

var path = require('path');

module.exports = function(grunt) {
  grunt.initConfig({
    copy: {
      build: {
        cwd: 'src/',
        src: ['**'],
        dest: 'build/',
        flatten: false,
        filter: 'isFile',
        expand: true
      },
      freedom: {
        src: [ require.resolve('freedom') ],
        dest: 'build/',
        flatten: true,
        filter: 'isFile',
        expand: true,
        onlyIf: 'modified'
      },
      browserbox: {
        cwd: path.dirname(require.resolve('browserbox')),
        src: [ 'browserbox.js',
               'browserbox-imap.js' ],
        dest: 'build/',
        expand: true,
        onlyIf: 'modified'
      }
    },

    browserify: {
      smtp: {
        files: {
          'build/smtp-connection.js': [
            path.dirname(require.resolve('smtp-connection')) +
              'src/smtp-connection.js'
          ]
        },
        options: {
          browserifyOptions: {
            standalone: 'SMTPConnection'
          }
        } 
      },
      compressionWorker: {
        files: {
          'build/compressionWorker.js': [
            path.dirname(require.resolve('browserbox')) +
              'browserbox-compression-worker.js'
          ]
        },
        options: {
          browserifyOptions: {
            standalone: 'Compression'
          }
        }
      },
    },

    jshint: {
      all: ['src/**/*.js', 'spec/**/*.js'],
      options: {
        jshintrc: true,
        ignores: ['src/forge.min.js']
      }
    },

    connect: {
      demo: {
        options: {
          port: 8000,
          keepalive: true,
          base: ['./', 'build/'],
          open: 'http://localhost:8000/build/demo/main.html'
        }
      }
    },

    clean: ['build/']
  });

  grunt.loadNpmTasks('grunt-browserify');
  grunt.loadNpmTasks('grunt-contrib-clean');
  grunt.loadNpmTasks('grunt-contrib-connect');
  grunt.loadNpmTasks('grunt-contrib-copy');
  grunt.loadNpmTasks('grunt-contrib-jshint');

  grunt.registerTask('build', [
    'jshint',
    'copy',
    'browserify'
  ]);
  grunt.registerTask('demo', [
    'build',
    'connect'
  ]);
  grunt.registerTask('default', [
    'build'
  ]);

};
