/**
 * Gruntfile for freedom-social-email
 *
 * Autogenerated by https://github.com/freedomjs/generator-freedom
 **/

var path = require('path');

module.exports = function(grunt) {
  require('time-grunt')(grunt);
  require('jit-grunt')(grunt, {
    jasmine_node: 'grunt-jasmine-node2',
    'npm-publish': 'grunt-npm'
  });

  grunt.initConfig({
    copy: {
      build: {
        cwd: 'src/',
        src: ['**'],
        dest: 'build/',
        flatten: false,
        filter: 'isFile',
        expand: true
      },
      freedom: {
        src: [ require.resolve('freedom') ],
        dest: 'build/',
        flatten: true,
        filter: 'isFile',
        expand: true,
        onlyIf: 'modified'
      }
    },

    browserify: {
      emailjs: {
        files: {
          'build/emailjs-imap.js': [ require.resolve('emailjs-imap-client') ],
          'build/emailjs-smtp.js': [ require.resolve('emailjs-smtp-client') ]
        }
      }
    },

    jshint: {
      all: ['src/**/*.js', 'spec/**/*.js'],
      options: {
        jshintrc: true
      }
    },

    // TODO make client demo
    /*connect: {
      demo: {
      options: {
      port: 8000,
      keepalive: true,
      base: ['./', 'build/'],
      open: 'http://localhost:8000/build/'
      }
      }
      },*/

    clean: ['build/']
  });

  grunt.registerTask('build', [
    'jshint',
    'copy',
    'browserify:emailjs'
  ]);
  grunt.registerTask('demo', [
    'build',
    //'connect'
  ]);
  grunt.registerTask('default', [
    'build'
  ]);

}
