/**
 * Gruntfile for freedom-social-email
 *
 * Autogenerated by https://github.com/freedomjs/generator-freedom
 **/

var path = require('path');

module.exports = function(grunt) {
  grunt.initConfig({
    copy: {
      build: {
        cwd: 'src/',
        src: ['**'],
        dest: 'build/',
        flatten: false,
        filter: 'isFile',
        expand: true
      },
      freedom: {
        src: [ require.resolve('freedom') ],
        dest: 'build/',
        flatten: true,
        filter: 'isFile',
        expand: true,
        onlyIf: 'modified'
      },
      browserbox: {
        cwd: path.dirname(require.resolve('browserbox')),
        src: [ 'browserbox.js',
               'browserbox-imap.js' ],
        dest: 'build/',
        expand: true,
        onlyIf: 'modified'
      }
    },

    browserify: {
      emailjs: {
        files: {
          'build/emailjs.js': [ require.resolve('emailjs') ]
        }
      }
    },

    jshint: {
      all: ['src/**/*.js', 'spec/**/*.js'],
      options: {
        jshintrc: true
      }
    },

    // TODO make client demo
    /*connect: {
      demo: {
      options: {
      port: 8000,
      keepalive: true,
      base: ['./', 'build/'],
      open: 'http://localhost:8000/build/'
      }
      }
      },*/

    clean: ['build/']
  });

  grunt.loadNpmTasks('grunt-browserify');
  grunt.loadNpmTasks('grunt-contrib-clean');
  //grunt.loadNpmTasks('grunt-contrib-connect');
  grunt.loadNpmTasks('grunt-contrib-copy');
  grunt.loadNpmTasks('grunt-contrib-jshint');

  grunt.registerTask('build', [
    'jshint',
    'copy',
    'browserify:emailjs'
  ]);
  grunt.registerTask('demo', [
    'build',
    //'connect'
  ]);
  grunt.registerTask('default', [
    'build'
  ]);

}
